---
title: "Researcher Development Report for 2025"
subtitle: "Joint Report from RDS & OGR Teams (Sept 30, 2025)"
# subtitle: "Data script for Preprocessing the training data"
#author: "Jen Beaudry"
#date: "29/09/2025"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}

# just a reminder that there is no output from this script. It just cleans the data.
  # I have built it as a Rmd so we can run it as a child document.

knitr::opts_chunk$set(echo = FALSE,
                      include = FALSE, 
                      eval = TRUE)


options(knitr.duplicate.label = "allow") # use this when you use the child files

# team names -- I use these names interchangeably 
  # RDS = RTDC
  # OGR = HDR

```


```{r library}

# Function to load or install packages
load_or_install <- function(packages) {
  for (package in packages) {
    if (!require(package, character.only = TRUE)) {
      install.packages(package, dependencies = TRUE)
      library(package, character.only = TRUE)
    }
  }
}

# Required packages 
packages <- c("here"
              , "tidyverse"
              , "readxl"
              , "janitor"
              , "rmarkdown"
              )

# Load or install the packages
load_or_install(packages)

rm(packages)
```

```{r load all training data}

# [breadcrumb: in the future, we could bring all HDR data cleaning into this script, 
  # rather than load data that's already been coded]

# load data from the RTDC training spreadsheet (this is the complete number of attendees
  # & includes info about the theme)

df_sp <- read_xlsx(
  here::here("data",
             "RDS",
             "2025_spreadsheet_data.xlsx"),
  sheet = '2025 Program',
  skip = 5, #start at the header row
  n_max = 94,  #last session was DP EOI
  .name_repair = "unique",
  trim_ws = TRUE) %>% 
  clean_names()

# load RTDC data from ienrol (this contains names of Flinders attendees & includes college/portfolio info)

df_ienrol <- read_csv(here::here("data", "RDS", "2025_ienrol_data.csv"), lazy = FALSE) %>% 
  clean_names()

df_hdr <- read_csv(here::here("data", "HDR", "hdr_complete.csv"), lazy = FALSE) 

```

```{r RDS delete sessions that did not run, eval = FALSE}

# delete the sessions that were scheduled but not run [will need to compare to our training spreadsheet]
  # use the n_courses code in the next chunk to make it easy to figure out which sessions didn't run

df_remove1 <- df_ienrol %>% 
  filter(course_name == "ARC Discovery Projects EOI PItching Session for CHASS/CEPSW/CBGL" & event_num == "3")

list_df <- list(df_ienrol, df_remove1, df_remove2, df_remove3, df_remove4)

df_ienrol <- list_df %>%reduce(anti_join)

rm(df_remove1, df_remove2, df_remove3, df_remove4, list_df)

```

```{r clean hdr data}

df_hdr <- df_hdr %>% 
  mutate (theme = case_when(role == "supervisor" ~ "HDR supervisors", 
                            role == "student" ~ "HDR students")) %>% 
  mutate (team = "OGR") %>% 
  rename(first_name = forename,
         last_name = surname) %>% 
  mutate (role = case_when (role == "supervisor" ~ "Academic", 
                                  role == "student" ~ "Student"))

# turn them into factors

cols <- c("event_num",
          "course_name",
             "college",
             "attendance_status",
          "role", 
          "modality",
          "training_category", 
          "theme")


df_hdr <- df_hdr %>% 
  dplyr::mutate(across(all_of(cols), ~factor(.))) 

# recode status and department so it matches the RTDC data

df_hdr <- df_hdr %>% 
  dplyr::mutate(portfolio = case_when (is.na(college) ~ "Other",
                                    TRUE ~ as.factor(as.character(college)))) %>% 
  relocate(portfolio, .after = college) %>% 
#  mutate(department = college) %>% # add this so we can run the same code in the report as we do with ienrol [or maybe not]
  select(-college) %>% 
  filter (course_name != "Research Town Hall with the Chief Scientist", # remove course from 2024
          course_name != "HDR Supervision: Industry Engagement for Researchers - panel discussion", # remove duplicate w/ our data
          course_name != "HDR Supervision: Mentee Roundtable") # remove duplicate w/ our data

# check that we have all the data we need
  # summarise the data based on how many courses were held and how many folks attended each of the sessions
  # we are going to keep more variables than I normally would because we are going to use this df to join
  # this hdr data to our spreadsheet. I don't want to have to do this again later.

n_courses_hdr <- df_hdr %>% 
  select(c(theme, team, course_name, event_num, modality, data_source, attendance_status, fan)) %>% 
  filter(attendance_status == "Attended") %>% 
  count(theme, team, course_name, event_num, modality, data_source, course_name, event_num) %>% 
  rename(registered = n)


# any course with zero attendees will not show up in n_courses. We need to manually add them back in. 
  # Dani said (meeting 15/10/2025) that they wouldn't have run any session with 0 attendees, so 
  # she asked that I remove those from the file. So, have only included courses with attendees. 
  # keeping the code just in case I need to do this again. 

# n_courses_all_hdr <- df_hdr %>% 
#   select(c(theme, team, course_name, event_num, modality, data_source, attendance_status, fan)) %>% 
# #  filter(attendance_status == "Attended") %>% 
#   count(theme, team, course_name, event_num, modality, data_source, course_name, event_num) %>% 
#   rename(registered = n)
# 
# n_courses_att_hdr <- df_hdr %>% 
#   select(c(theme, team, course_name, event_num, modality, data_source, attendance_status, fan)) %>% 
#   filter(attendance_status == "Attended") %>% 
#   count(theme, team, course_name, event_num, modality, data_source, course_name, event_num) %>% 
#   rename(attended = n)

# need to find them first:
# 
# check <- anti_join (n_courses_all_hdr, n_courses_att_hdr, by = join_by("course_name", "event_num"))
# 
# add_df <- list(course_name = c("3MT Workshop/Practice Sessions", 
#                "HDR Development Drop-in Sessions",
#                "HDR Development Drop-in Sessions",
#                "HDR Development Drop-in Sessions",
#                 "HDR Development Drop-in Sessions",
#                "HDR Development Drop-in Sessions"),
#           event_num = c("7", "4", "14", "15", "20", "25"),
#           theme = "HDR students", 
#           team = "OGR",
#           modality = "synchronous",
#           n = "0") %>% as_tibble %>%
#   mutate(
#     course_name = as.factor(course_name),
#     event_num = as.factor(event_num),
#     attended = as.integer(n))
# 
# # use this df later to join to our spreadsheet data
# n_courses_hdr <- full_join(n_courses_att_hdr,add_df) %>% 
#   select(-n)
# 
# rm(add_df, check, n_courses_all_hdr, n_courses_att_hdr)

```

```{r clean ienrol data}

df_ienrol <- df_ienrol %>%
  select (c(course_name, event_num, first_name, last_name, fan, department, job_status, status)) %>% 
  mutate (team = "RDS", 
          modality = "synchronous", 
          data_source = "ienrol") %>% 
  rename (role = job_status)


# turn them into factors

cols <- c("course_name",
          "event_num",
             "department",
             "role",
             "status", 
            "team")

# recode status and department

df_ienrol <- df_ienrol %>% 
  dplyr::mutate(across(all_of(cols), ~factor(.))) %>% 
  dplyr::mutate(attendance_status = case_when (status == "attended" ~ "Attended", 
                                        status == "didnotattend" ~ "Did not attend")) %>% 
  dplyr::mutate(portfolio = case_when (grepl("Research", department) ~ "Portfolio of the Deputy Vice-Chancellor (Research)", #recode RDS as DVC(R)
                                    !grepl("College of", department) ~ "Other portfolios",
                                    department == "Other" ~ "Other",
                                    department == "Unknown" ~ "Other", 
                                    TRUE ~ as.factor(as.character(department)))) %>% 
  select(-status)


# summarise the data based on how many courses were held and how many folks attended each of the sessions

n_courses_all_rds <- df_ienrol %>% 
#  filter(attendance_status == "Attended") %>% 
  count(course_name, event_num, data_source)

n_courses_rds <- df_ienrol %>% 
  filter(attendance_status == "Attended") %>% 
  count(course_name, event_num, data_source)

# any course with zero attendees will not show up in n_courses. We need to manually add them back in. 
  # 2025: we don't seem to have any courses that were not included, so skip this for now. 

# add_df <- list(course_name = "Research Ethics & Biosafety Applications Hands-on Workshop", 
#           event_num = "3", 
#           n = "0") %>% as_tibble %>% 
#   mutate(
#     course_name = as.factor(course_name), 
#     event_num = as.factor(event_num), 
#     n = as.integer(n))

# n_courses <- full_join(n_courses,add_df) 

# rm(add_df)

```

```{r clean spreadsheet data}

df_sp <- df_sp %>% 
   dplyr::rename(attended = no_attended, 
                 attended_in_person = no_in_person_attendees, 
                 attended_online = no_online_attendees, 
                 course_name = session) %>%
  select(c(theme, event, attended, course_name, attended_in_person, attended_online)) %>% 
  mutate(team = "RDS", 
         modality = "synchronous",
         data_source = "training spreadsheet")


# rename these themes in the spreadsheet (before we turn theme into a factor)
  
df_sp [df_sp == "FNRC"] <- "First Nations Researchers Collective"
df_sp [df_sp == "Commerce"] <- "Post-award, Intellectual Property, and Commercialisation"

# turn them into factors

cols <- c("course_name",
          "event",
          "theme",
          "modality",
          "data_source",
            "team")

df_sp <- df_sp %>% 
  dplyr::mutate(across(all_of(cols), ~factor(.)))

# this number will differ from the T&D spreadsheet because we have had attendees that are not in iEnrol

n_attended_sp <- sum(df_sp$attended)

```

```{r identify joint sessions}

df_sp <- df_sp %>% 
    dplyr::mutate(team = case_when (course_name == "Researcher Mentoring Program: Mentee Roundtable #2" ~ "Joint", 
                                    course_name == "Industry Engagement for Researchers Panel discussion" ~ "Joint", 
                                    TRUE ~ as.factor(as.character(team)))) 

```

<!-- I ONLY NEED TO RUN THIS TO COMPARE IENROL TO SPREADSHEET DATA -->
<!-- Number of courses shown in spreadsheet = `r nrow(df_sp)` -->

```{r show all spreadsheet courses, include = TRUE, eval = FALSE}

#combine sessions & attendees per theme
simple_df_sp <- df_sp %>% 
  select (c(course_name, attended, data_source)) %>% 
  dplyr::arrange(course_name) # put it in alphabetical order


# make it look good
kable(simple_df_sp, 
      booktabs = T,
      align = c('lcc'), 
      caption = "Sessions recorded in spreadsheet for 2025",
      linesep = "\\addlinespace") %>% 
  kable_styling(latex_options = c("hold_position", "striped")) 

```

<!-- I use the following code to find the issues. But we don't need to run them with the full report. -->
<!-- Number of courses shown in iEnrol, with registrations = `r nrow(n_courses)`. Compare this to the number of rows in df_sp. -->

```{r show all ienrol courses with registrations, include = TRUE, eval = FALSE}

# make it look good
kable(n_courses_all_rds, 
      booktabs = T,
      align = c('lccc'), 
      caption = "Sessions recorded in iEnrol for 2025; N shows all registrations, not only attendees",
      linesep = "\\addlinespace") %>% 
  kable_styling(latex_options = c("hold_position", "striped")) 

```

<!-- Number of courses shown in iEnrol, with attendees = `r nrow(n_courses)` -->

```{r show all ienrol courses with attendees, include = TRUE, eval = FALSE}

# make it look good
kable(n_courses_rds, 
      booktabs = T,
      align = c('lccc'), 
      caption = "Sessions recorded in iEnrol for 2025; N shows only attendees",
      linesep = "\\addlinespace") %>% 
  kable_styling(latex_options = c("hold_position", "striped")) 

# compare all ienrol courses with registrations to courses with attendees
n_compare_rds <- anti_join(n_courses_all_rds, n_courses_rds, by = c("course_name", "event_num"))

# this is text that didn't work for some reason. Use it when you're first cleaning the data
# Number of courses shown in iEnrol, with registrations = `r nrow(n_courses_all)`

```

```{r compare all ienrol courses with registrations to courses with attendees, incl = FALSE, eval = FALSE}

# make it look good
kable(n_compare_rds, 
      booktabs = T,
      align = c('lccc'), 
      caption = "Sessions that are in the ienrol registrations without attendees",
      linesep = "\\addlinespace") %>% 
  kable_styling(latex_options = c("hold_position", "striped")) 

```

```{r compare all ienrol courses with courses in our spreadsheet, incl = FALSE, eval = FALSE}

# 2025: we have more sessions in our spreadsheet than in ienrol, so now I have to figure out which ones...

# compare the two tibbles & see what doesn't match. 
ienrol_vs_sp <- anti_join(n_courses_rds, df_sp, by = "course_name")
sp_vs_ienrol <- anti_join(df_sp, n_courses_rds, by = "course_name")

rm(ienrol_vs_sp, sp_vs_ienrol)

```


```{r join the spreadsheet and hdr data}

# use the data we cleaned earlier to figure out how many courses were included
  # in the hdr data

sp_hdr <- full_join(n_courses_hdr, df_sp)

```


```{r join the ienrol and hdr data}

ienrol_hdr <- full_join(df_hdr, df_ienrol)

```


```{r write the preprocessed data}

# when done preprocessing, write the data to new files
# row.names gets rid of the first column from the dataframe.

write.csv(df_hdr, here::here("data", "processed", "hdr_processed.csv"), row.names = FALSE)

write.csv(df_ienrol, here::here("data", "processed", "ienrol_processed.csv"), row.names = FALSE)

write.csv(df_sp, here::here("data", "processed", "spreadsheet_processed.csv"), row.names = FALSE)

write.csv(ienrol_hdr, here::here("data", "processed", "joined_ienrol_hdr_processed.csv"), row.names = FALSE)

write.csv(sp_hdr, here::here("data", "processed", "joined_spreadsheet_hdr_processed.csv"), row.names = FALSE)

```
